sudo: required
dist: trusty
language: python

python:
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - >
    sudo apt-get install -qq --install-recommends
    git-buildpackage devscripts build-essential python3-dev
    libsnmp-dev python3-yaml python3-mock python3 python3-pip

install:
  - sudo pip3 install coveralls
  - sudo ln -sf /usr/local/bin/coverage3 /usr/local/bin/python3-coverage

script:
  - make
  - sudo make install

after_success:
  - coveralls

before_deploy:
  - gem install mime-types -v 2.6.2
