apiVersion: v1
kind: Service
metadata:
  labels:
    app: snmpexporter
  name: prober
  namespace: prod
spec:
  ports:
  - name: probe
    port: 9190
    protocol: TCP
    targetPort: 9190
  selector:
    app: snmpexporter
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: snmpexporter
  name: snmpexporter
  namespace: prod
spec:
  replicas: 20
  selector:
    matchLabels:
      app: snmpexporter
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 5
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snmpexporter
      name: snmpexporter
    spec:
      containers:
      - image: quay.io/dhtech/snmpexporter
        imagePullPolicy: Always
        name: snmpexporter
        volumeMounts:
          - name: config-volume
            mountPath: /etc/snmpexporter
        resources:
              requests:
                memory: "300Mi"
              limits:
                memory: "400Mi"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 9190
          initialDelaySeconds: 15
          timeoutSeconds: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: snmpexporter
---
