apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: snmpexporterd
  name: snmpexporterd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: snmpexporterd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snmpexporterd
      name: snmpexporterd
    spec:
      nodeSelector:
        # TODO(bluecmd): As we have the NAT asymetry problem, stick this to
        # a single machine for now.
        kubernetes.io/hostname: cloud0
      containers:
      - image: val.tech.dreamhack.se/snmpexporterd
        imagePullPolicy: Always
        name: snmpexporterd
        volumeMounts:
          - name: config-volume
            mountPath: /etc/snmpexporter
      dnsPolicy: Default
      imagePullSecrets:
      - name: tech-registry-key
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: snmpexporter
